# Generated by Django 5.2.15 on 2026-07-06 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pakistanialternative',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes visible only to admins'),
        ),
        migrations.AddField(
            model_name='pakistanialternative',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Shown to the submitter when rejected or needs changes'),
        ),
        migrations.AddField(
            model_name='pakistanialternative',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pakistanialternative',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_alternatives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pakistanialternative',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_alternatives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pakistanialternative',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_changes', 'Needs Changes')], default='pending', max_length=15),
        ),
    ]
