# Generated by Django 5.2.15 on 2026-07-25 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='boycottproduct',
            name='idx_product_verified_active',
        ),
        migrations.RemoveIndex(
            model_name='pakistanialternative',
            name='idx_alternative_status_active',
        ),
        migrations.AlterField(
            model_name='alternativevote',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
