# Generated by Django 5.2.15 on 2026-07-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternative',
            name='local_image',
            field=models.CharField(blank=True, help_text='Local image path under static/img/alternative/', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='local_image',
            field=models.CharField(blank=True, help_text='Local image path under static/img/boycott/', max_length=255),
        ),
    ]
