# Generated by Django 5.2.15 on 2026-07-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_local_image_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternative',
            name='local_image',
            field=models.CharField(blank=True, help_text='Local image path under static/img/alternative/', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='local_image',
            field=models.CharField(blank=True, help_text='Local image path under static/img/boycott/', max_length=255, null=True),
        ),
    ]
